package com.biit.webforms.condition.parser.expressions;

/*-
 * #%L
 * Pilot Agile Testing for WebForms (Expression parser)
 * %%
 * Copyright (C) 2014 - 2025 BiiT Sourcing Solutions S.L.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import com.biit.form.entity.BaseQuestion;
import com.biit.webforms.persistence.entity.Form;
import com.biit.webforms.utils.math.domain.IDomain;

/**
 * Interface implemented by all the expressions generated by the webforms parser
 * from the flow condition tokens.
 *
 */
public interface WebformsExpression {

	/**
	 * Returns the logic domain.
	 *
	 * @return
	 */
	public IDomain getDomain();

	/**
	 * Checks the possibility of a block issue generated by minterm. This check
	 * is done at expression level to contemplate the and/or/parenthesis
	 * possibilities.
	 *
	 * @param form
	 * @param element
	 * @return
	 */
	public boolean checkBlockByMinTerms(Form form, BaseQuestion element);
	
	/**
	 * Evaluate logic
	 * @return
	 */
	public Boolean evaluate();

}
