package com.biit.webforms.condition.parser.expressions;

import com.biit.form.entity.BaseQuestion;
import com.biit.webforms.persistence.entity.Form;
import com.biit.webforms.utils.math.domain.IDomain;

/**
 * Interface implemented by all the expressions generated by the webforms parser
 * from the flow condition tokens.
 *
 */
public interface WebformsExpression {

	/**
	 * Returns the logic domain.
	 * 
	 * @return
	 */
	public IDomain getDomain();

	/**
	 * Checks the possibility of a block issue generated by minterm. This check
	 * is done at expression level to contemplate the and/or/parenthsis
	 * possibilities.
	 * 
	 * @param form
	 * @param element
	 * @return
	 */
	public boolean checkBlockByMinTerms(Form form, BaseQuestion element);
	
	/**
	 * Evaluate logic
	 * @return
	 */
	public Boolean evaluate();

}
