package com.biit.webforms.persistence.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.biit.form.TreeObject;
import com.biit.form.exceptions.NotValidTreeObjectException;
import com.biit.persistence.entity.StorableObject;
import com.biit.persistence.entity.exceptions.NotValidStorableObjectException;

@Entity
@Table(name = "tree_texts")
public class Text extends WebformsBaseQuestion {
	// Name is autogenerated by application.
	// Label is ignored
	// Description holds the text.
	public static final int MAX_DESCRIPTION_LENGTH = 10000;
	public static final int MAX_DESCRIPTION_LABEL = 30;

	@Column(length = MAX_DESCRIPTION_LENGTH, columnDefinition = "varchar(" + MAX_DESCRIPTION_LENGTH + ")")
	private String description;

	public Text() {
		super();
		description = new String();
	}

	@Override
	protected List<Class<? extends TreeObject>> getAllowedChildren() {
		return new ArrayList<Class<? extends TreeObject>>();
	}

	@Override
	public void copyData(StorableObject object) throws NotValidStorableObjectException {
		if (object instanceof Text) {
			// Copy basic data and description
			copyBasicInfo(object);
			description = new String(((Text) object).getDescription());
		} else {
			throw new NotValidTreeObjectException("Copy data for Text only supports the same type copy");
		}
	}

	@Override
	public String getLabel() {
		if (description.length() > MAX_DESCRIPTION_LABEL) {
			return description.substring(0, MAX_DESCRIPTION_LABEL) + "...";
		}
		return description;
	}

	@Override
	public void setLabel(String label) {
		// Ignore
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int exportToJavaCode(StringBuilder sb, int counter) {
		String idName = "el_" + counter;
		
		sb.append("Text ").append(idName).append("  = new Text();").append(System.lineSeparator());
		sb.append(idName).append(".setName(\"").append(this.getName()).append("\");").append(System.lineSeparator());
		sb.append(idName).append(".setDescription(\"").append(this.getDescription()).append("\");").append(System.lineSeparator());

		return counter;
	}
	
	/**
	 * Compares the content of treeObject - Needs to be an instance of Text
	 * 
	 * @param treeObject
	 * @return
	 */
	public boolean isContentEqual(TreeObject treeObject) {
		if (treeObject instanceof Text) {
			if(super.isContentEqual(treeObject)){
				Text text = (Text) treeObject;
				if(this.getDescription()!=null && !this.getDescription().equals(text.getDescription())){
					return false;
				}
				return true;
			}
		}
		return false;
	}
}
