package com.biit.webforms.flow;

import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

import com.biit.form.entity.BaseQuestion;
import com.biit.form.entity.TreeObject;
import com.biit.webforms.persistence.entity.Flow;
import com.biit.webforms.persistence.entity.Form;

/**
 * This class removes all unnecessary or repeated flows that are generated by
 * the normal operation of the user with the form designer
 *
 */
public class FlowCleaner {

	private Form form;
	private Set<Flow> otherFlowsRemoved;
	private Set<Flow> uselessFlowRemoved;

	public FlowCleaner(Form form) {
		this.form = form;
		otherFlowsRemoved = new HashSet<>();
		uselessFlowRemoved = new HashSet<>();
	}

	public void cleanFlow() {
		LinkedHashSet<BaseQuestion> questions = form.getAllChildrenInHierarchy(BaseQuestion.class);
		Iterator<BaseQuestion> questionIterator = questions.iterator();
		BaseQuestion question = null;
		BaseQuestion nextQuestion = null;
		while (questionIterator.hasNext()) {
			nextQuestion = questionIterator.next();
			if (question != null) {
				Set<Flow> flows = form.getFlowsFrom(question);
				clearInvalidOthersFlow(question, flows);
				removeUselessFlows(question, nextQuestion, flows);
			}
			question = nextQuestion;
		}
	}

	/**
	 * Clear all the single exit OTHER flows of a node.
	 * 
	 * @param question
	 * @param flows
	 */
	private void clearInvalidOthersFlow(TreeObject question, Set<Flow> flows) {
		// Others is not allowed if is the only question.
		if (flows.size() == 1) {
			Flow flow = flows.iterator().next();
			if (!flow.isReadOnly() && flow.isOthers()) {
				flow.setOthers(false);
				// Add a copy because maybe changed by other rules.
				otherFlowsRemoved.add(flow.generateCopy());
			}
		}
	}

	/**
	 * Remove empty single flow flows to the next element
	 * 
	 * @param question
	 * @param nextQuestion
	 * @param flows
	 */
	private void removeUselessFlows(BaseQuestion question, BaseQuestion nextQuestion, Set<Flow> flows) {
		// One flow without condition that goes to next element, is the default
		// one, we can remove it.
		if (flows.size() == 1) {
			Flow flow = flows.iterator().next();
			// Flow point to nextQuestion.
			if ((flow != null) && (flow.getDestiny() != null) && (nextQuestion != null)) {
				if (!flow.isReadOnly() && flow.getDestiny().equals(nextQuestion)) {
					// Has no condition.
					if (flow.getComputedCondition() == null || flow.getComputedCondition().isEmpty()) {
						form.removeRule(flow);
						uselessFlowRemoved.add(flow);
					}
				}
			}
		}
	}

	public Set<Flow> getOtherFlowsRemoved() {
		return otherFlowsRemoved;
	}

	public Set<Flow> getUselessFlowRemoved() {
		return uselessFlowRemoved;
	}

}
